version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/collaborative-task-app
    command: sleep infinity
    depends_on:
      - db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
      DJANGO_SECRET_KEY: "g+52)a(_r19$!t0kd^qzpw__-l!0-s#yq2fzg-+ei23v2tm&&%"
    networks:
      - dev-network

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    networks:
      - dev-network
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  dev-network: