version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/collaborative-task-app
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://app_user:app_password@db:5432/app_db
    networks:
      - dev-network

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    networks:
      - dev-network

volumes:
  postgres-data:

networks:
  dev-network: